export default {
  playableBoard: [
    [
      {
        guess: '',
        answer: 'M',
        number: 1,
        clues: ['1A', '1D'],
      },
      {
        guess: '',
        answer: 'I',
        number: 2,
        clues: ['1A', '2D'],
      },
      {
        guess: '',
        answer: 'A',
        number: 3,
        clues: ['1A', '3D'],
      },
      {
        answer: '#BlackSquare#',
      },
      {
        guess: '',
        answer: 'C',
        number: 4,
        clues: ['4A', '4D'],
      },
      {
        guess: '',
        answer: 'A',
        number: 5,
        clues: ['4A', '5D'],
      },
      {
        guess: '',
        answer: 'N',
        number: 6,
        clues: ['4A', '6D'],
      },
      {
        guess: '',
        answer: 'E',
        number: 7,
        clues: ['4A', '7D'],
      },
      {
        guess: '',
        answer: 'S',
        number: 8,
        clues: ['4A', '8D'],
      },
      {
        answer: '#BlackSquare#',
      },
      {
        guess: '',
        answer: 'S',
        number: 9,
        clues: ['9A', '9D'],
      },
      {
        guess: '',
        answer: 'P',
        number: 10,
        clues: ['9A', '10D'],
      },
      {
        guess: '',
        answer: 'O',
        number: 11,
        clues: ['9A', '11D'],
      },
      {
        guess: '',
        answer: 'O',
        number: 12,
        clues: ['9A', '12D'],
      },
      {
        guess: '',
        answer: 'L',
        number: 13,
        clues: ['9A', '13D'],
      },
    ],
    [
      {
        guess: '',
        answer: 'I',
        number: 14,
        clues: ['14A', '1D'],
      },
      {
        guess: '',
        answer: 'N',
        number: null,
        clues: ['14A', '2D'],
      },
      {
        guess: '',
        answer: 'V',
        number: null,
        clues: ['14A', '3D'],
      },
      {
        guess: '',
        answer: 'A',
        number: 15,
        clues: ['14A', '15D'],
      },
      {
        guess: '',
        answer: 'R',
        number: null,
        clues: ['14A', '4D'],
      },
      {
        guess: '',
        answer: 'I',
        number: null,
        clues: ['14A', '5D'],
      },
      {
        guess: '',
        answer: 'A',
        number: null,
        clues: ['14A', '6D'],
      },
      {
        guess: '',
        answer: 'N',
        number: null,
        clues: ['14A', '7D'],
      },
      {
        guess: '',
        answer: 'T',
        number: null,
        clues: ['14A', '8D'],
      },
      {
        answer: '#BlackSquare#',
      },
      {
        guess: '',
        answer: 'C',
        number: 16,
        clues: ['16A', '9D'],
      },
      {
        guess: '',
        answer: 'A',
        number: null,
        clues: ['16A', '10D'],
      },
      {
        guess: '',
        answer: 'T',
        number: null,
        clues: ['16A', '11D'],
      },
      {
        guess: '',
        answer: 'T',
        number: null,
        clues: ['16A', '12D'],
      },
      {
        guess: '',
        answer: 'Y',
        number: null,
        clues: ['16A', '13D'],
      },
    ],
    [
      {
        guess: '',
        answer: 'C',
        number: 17,
        clues: ['17A', '1D'],
      },
      {
        guess: '',
        answer: 'R',
        number: null,
        clues: ['17A', '2D'],
      },
      {
        guess: '',
        answer: 'O',
        number: null,
        clues: ['17A', '3D'],
      },
      {
        guess: '',
        answer: 'C',
        number: null,
        clues: ['17A', '15D'],
      },
      {
        guess: '',
        answer: 'O',
        number: null,
        clues: ['17A', '4D'],
      },
      {
        guess: '',
        answer: 'D',
        number: null,
        clues: ['17A', '5D'],
      },
      {
        guess: '',
        answer: 'I',
        number: null,
        clues: ['17A', '6D'],
      },
      {
        guess: '',
        answer: 'L',
        number: null,
        clues: ['17A', '7D'],
      },
      {
        guess: '',
        answer: 'E',
        number: null,
        clues: ['17A', '8D'],
      },
      {
        answer: '#BlackSquare#',
      },
      {
        guess: '',
        answer: 'A',
        number: 18,
        clues: ['18A', '9D'],
      },
      {
        guess: '',
        answer: 'U',
        number: null,
        clues: ['18A', '10D'],
      },
      {
        guess: '',
        answer: 'R',
        number: null,
        clues: ['18A', '11D'],
      },
      {
        guess: '',
        answer: 'I',
        number: null,
        clues: ['18A', '12D'],
      },
      {
        guess: '',
        answer: 'C',
        number: null,
        clues: ['18A', '13D'],
      },
    ],
    [
      {
        guess: '',
        answer: 'K',
        number: 19,
        clues: ['19A', '1D'],
      },
      {
        guess: '',
        answer: 'E',
        number: null,
        clues: ['19A', '2D'],
      },
      {
        guess: '',
        answer: 'N',
        number: null,
        clues: ['19A', '3D'],
      },
      {
        guess: '',
        answer: 'T',
        number: null,
        clues: ['19A', '15D'],
      },
      {
        answer: '#BlackSquare#',
      },
      {
        guess: '',
        answer: 'E',
        number: 20,
        clues: ['20A', '5D'],
      },
      {
        guess: '',
        answer: 'L',
        number: null,
        clues: ['20A', '6D'],
      },
      {
        guess: '',
        answer: 'I',
        number: null,
        clues: ['20A', '7D'],
      },
      {
        guess: '',
        answer: 'W',
        number: null,
        clues: ['20A', '8D'],
      },
      {
        guess: '',
        answer: 'A',
        number: 21,
        clues: ['20A', '21D'],
      },
      {
        guess: '',
        answer: 'L',
        number: null,
        clues: ['20A', '9D'],
      },
      {
        guess: '',
        answer: 'L',
        number: null,
        clues: ['20A', '10D'],
      },
      {
        guess: '',
        answer: 'A',
        number: null,
        clues: ['20A', '11D'],
      },
      {
        guess: '',
        answer: 'C',
        number: null,
        clues: ['20A', '12D'],
      },
      {
        guess: '',
        answer: 'H',
        number: null,
        clues: ['20A', '13D'],
      },
    ],
    [
      {
        answer: '#BlackSquare#',
      },
      {
        answer: '#BlackSquare#',
      },
      {
        answer: '#BlackSquare#',
      },
      {
        guess: '',
        answer: 'S',
        number: 22,
        clues: ['22A', '15D'],
      },
      {
        guess: '',
        answer: 'I',
        number: 23,
        clues: ['22A', '23D'],
      },
      {
        guess: '',
        answer: 'D',
        number: null,
        clues: ['22A', '5D'],
      },
      {
        guess: '',
        answer: 'E',
        number: null,
        clues: ['22A', '6D'],
      },
      {
        guess: '',
        answer: 'S',
        number: null,
        clues: ['22A', '7D'],
      },
      {
        answer: '#BlackSquare#',
      },
      {
        guess: '',
        answer: 'B',
        number: 24,
        clues: ['24A', '21D'],
      },
      {
        guess: '',
        answer: 'A',
        number: null,
        clues: ['24A', '9D'],
      },
      {
        guess: '',
        answer: 'H',
        number: null,
        clues: ['24A', '10D'],
      },
      {
        answer: '#BlackSquare#',
      },
      {
        answer: '#BlackSquare#',
      },
      {
        answer: '#BlackSquare#',
      },
    ],
    [
      {
        guess: '',
        answer: 'C',
        number: 25,
        clues: ['25A', '25D'],
      },
      {
        guess: '',
        answer: 'A',
        number: 26,
        clues: ['25A', '26D'],
      },
      {
        guess: '',
        answer: 'L',
        number: 27,
        clues: ['25A', '27D'],
      },
      {
        answer: '#BlackSquare#',
      },
      {
        guess: '',
        answer: 'B',
        number: 28,
        clues: ['28A', '23D'],
      },
      {
        guess: '',
        answer: 'E',
        number: null,
        clues: ['28A', '5D'],
      },
      {
        guess: '',
        answer: 'R',
        number: null,
        clues: ['28A', '6D'],
      },
      {
        guess: '',
        answer: 'T',
        number: null,
        clues: ['28A', '7D'],
      },
      {
        guess: '',
        answer: 'H',
        number: 29,
        clues: ['28A', '29D'],
      },
      {
        guess: '',
        answer: 'A',
        number: null,
        clues: ['28A', '21D'],
      },
      {
        answer: '#BlackSquare#',
      },
      {
        guess: '',
        answer: 'O',
        number: 30,
        clues: ['30A', '10D'],
      },
      {
        guess: '',
        answer: 'P',
        number: 31,
        clues: ['30A', '31D'],
      },
      {
        guess: '',
        answer: 'A',
        number: 32,
        clues: ['30A', '32D'],
      },
      {
        guess: '',
        answer: 'L',
        number: 33,
        clues: ['30A', '33D'],
      },
    ],
    [
      {
        guess: '',
        answer: 'A',
        number: 34,
        clues: ['34A', '25D'],
      },
      {
        guess: '',
        answer: 'M',
        number: null,
        clues: ['34A', '26D'],
      },
      {
        guess: '',
        answer: 'O',
        number: null,
        clues: ['34A', '27D'],
      },
      {
        guess: '',
        answer: 'L',
        number: 35,
        clues: ['34A', '35D'],
      },
      {
        guess: '',
        answer: 'E',
        number: null,
        clues: ['34A', '23D'],
      },
      {
        answer: '#BlackSquare#',
      },
      {
        answer: '#BlackSquare#',
      },
      {
        guess: '',
        answer: 'S',
        number: 36,
        clues: ['36A', '7D'],
      },
      {
        guess: '',
        answer: 'O',
        number: null,
        clues: ['36A', '29D'],
      },
      {
        guess: '',
        answer: 'T',
        number: null,
        clues: ['36A', '21D'],
      },
      {
        answer: '#BlackSquare#',
      },
      {
        guess: '',
        answer: 'G',
        number: 37,
        clues: ['37A', '10D'],
      },
      {
        guess: '',
        answer: 'A',
        number: null,
        clues: ['37A', '31D'],
      },
      {
        guess: '',
        answer: 'L',
        number: null,
        clues: ['37A', '32D'],
      },
      {
        guess: '',
        answer: 'A',
        number: null,
        clues: ['37A', '33D'],
      },
    ],
    [
      {
        guess: '',
        answer: 'R',
        number: 38,
        clues: ['38A', '25D'],
      },
      {
        guess: '',
        answer: 'E',
        number: null,
        clues: ['38A', '26D'],
      },
      {
        guess: '',
        answer: 'B',
        number: null,
        clues: ['38A', '27D'],
      },
      {
        guess: '',
        answer: 'O',
        number: null,
        clues: ['38A', '35D'],
      },
      {
        guess: '',
        answer: 'X',
        number: null,
        clues: ['38A', '23D'],
      },
      {
        guess: '',
        answer: 'E',
        number: 39,
        clues: ['38A', '39D'],
      },
      {
        guess: '',
        answer: 'D',
        number: 40,
        clues: ['38A', '40D'],
      },
      {
        answer: '#BlackSquare#',
      },
      {
        guess: '',
        answer: 'B',
        number: 41,
        clues: ['41A', '29D'],
      },
      {
        guess: '',
        answer: 'E',
        number: null,
        clues: ['41A', '21D'],
      },
      {
        guess: '',
        answer: 'L',
        number: 42,
        clues: ['41A', '42D'],
      },
      {
        guess: '',
        answer: 'A',
        number: null,
        clues: ['41A', '10D'],
      },
      {
        guess: '',
        answer: 'T',
        number: null,
        clues: ['41A', '31D'],
      },
      {
        guess: '',
        answer: 'E',
        number: null,
        clues: ['41A', '32D'],
      },
      {
        guess: '',
        answer: 'D',
        number: null,
        clues: ['41A', '33D'],
      },
    ],
    [
      {
        guess: '',
        answer: 'O',
        number: 43,
        clues: ['43A', '25D'],
      },
      {
        guess: '',
        answer: 'B',
        number: null,
        clues: ['43A', '26D'],
      },
      {
        guess: '',
        answer: 'A',
        number: null,
        clues: ['43A', '27D'],
      },
      {
        guess: '',
        answer: 'N',
        number: null,
        clues: ['43A', '35D'],
      },
      {
        answer: '#BlackSquare#',
      },
      {
        guess: '',
        answer: 'N',
        number: 44,
        clues: ['44A', '39D'],
      },
      {
        guess: '',
        answer: 'U',
        number: null,
        clues: ['44A', '40D'],
      },
      {
        guess: '',
        answer: 'B',
        number: 45,
        clues: ['44A', '45D'],
      },
      {
        answer: '#BlackSquare#',
      },
      {
        answer: '#BlackSquare#',
      },
      {
        guess: '',
        answer: 'E',
        number: 46,
        clues: ['46A', '42D'],
      },
      {
        guess: '',
        answer: 'N',
        number: null,
        clues: ['46A', '10D'],
      },
      {
        guess: '',
        answer: 'T',
        number: null,
        clues: ['46A', '31D'],
      },
      {
        guess: '',
        answer: 'R',
        number: null,
        clues: ['46A', '32D'],
      },
      {
        guess: '',
        answer: 'Y',
        number: null,
        clues: ['46A', '33D'],
      },
    ],
    [
      {
        guess: '',
        answer: 'M',
        number: 47,
        clues: ['47A', '25D'],
      },
      {
        guess: '',
        answer: 'A',
        number: null,
        clues: ['47A', '26D'],
      },
      {
        guess: '',
        answer: 'R',
        number: null,
        clues: ['47A', '27D'],
      },
      {
        guess: '',
        answer: 'C',
        number: null,
        clues: ['47A', '35D'],
      },
      {
        answer: '#BlackSquare#',
      },
      {
        guess: '',
        answer: 'O',
        number: 48,
        clues: ['48A', '39D'],
      },
      {
        guess: '',
        answer: 'D',
        number: null,
        clues: ['48A', '40D'],
      },
      {
        guess: '',
        answer: 'E',
        number: null,
        clues: ['48A', '45D'],
      },
      {
        guess: '',
        answer: 'S',
        number: 49,
        clues: ['48A', '49D'],
      },
      {
        guess: '',
        answer: 'S',
        number: 50,
        clues: ['48A', '50D'],
      },
      {
        guess: '',
        answer: 'A',
        number: null,
        clues: ['48A', '42D'],
      },
      {
        answer: '#BlackSquare#',
      },
      {
        guess: '',
        answer: 'I',
        number: 51,
        clues: ['51A', '31D'],
      },
      {
        guess: '',
        answer: 'T',
        number: null,
        clues: ['51A', '32D'],
      },
      {
        guess: '',
        answer: 'S',
        number: null,
        clues: ['51A', '33D'],
      },
    ],
    [
      {
        answer: '#BlackSquare#',
      },
      {
        answer: '#BlackSquare#',
      },
      {
        answer: '#BlackSquare#',
      },
      {
        guess: '',
        answer: 'H',
        number: 52,
        clues: ['52A', '35D'],
      },
      {
        guess: '',
        answer: 'A',
        number: 53,
        clues: ['52A', '53D'],
      },
      {
        guess: '',
        answer: 'L',
        number: null,
        clues: ['52A', '39D'],
      },
      {
        answer: '#BlackSquare#',
      },
      {
        guess: '',
        answer: 'A',
        number: 54,
        clues: ['54A', '45D'],
      },
      {
        guess: '',
        answer: 'M',
        number: null,
        clues: ['54A', '49D'],
      },
      {
        guess: '',
        answer: 'P',
        number: null,
        clues: ['54A', '50D'],
      },
      {
        guess: '',
        answer: 'H',
        number: null,
        clues: ['54A', '42D'],
      },
      {
        guess: '',
        answer: 'I',
        number: 55,
        clues: ['54A', '55D'],
      },
      {
        answer: '#BlackSquare#',
      },
      {
        answer: '#BlackSquare#',
      },
      {
        answer: '#BlackSquare#',
      },
    ],
    [
      {
        guess: '',
        answer: 'S',
        number: 56,
        clues: ['56A', '56D'],
      },
      {
        guess: '',
        answer: 'A',
        number: 57,
        clues: ['56A', '57D'],
      },
      {
        guess: '',
        answer: 'L',
        number: 58,
        clues: ['56A', '58D'],
      },
      {
        guess: '',
        answer: 'A',
        number: null,
        clues: ['56A', '35D'],
      },
      {
        guess: '',
        answer: 'M',
        number: null,
        clues: ['56A', '53D'],
      },
      {
        guess: '',
        answer: 'A',
        number: null,
        clues: ['56A', '39D'],
      },
      {
        guess: '',
        answer: 'N',
        number: 59,
        clues: ['56A', '59D'],
      },
      {
        guess: '',
        answer: 'D',
        number: null,
        clues: ['56A', '45D'],
      },
      {
        guess: '',
        answer: 'E',
        number: null,
        clues: ['56A', '49D'],
      },
      {
        guess: '',
        answer: 'R',
        number: null,
        clues: ['56A', '50D'],
      },
      {
        answer: '#BlackSquare#',
      },
      {
        guess: '',
        answer: 'S',
        number: 60,
        clues: ['60A', '55D'],
      },
      {
        guess: '',
        answer: 'O',
        number: 61,
        clues: ['60A', '61D'],
      },
      {
        guess: '',
        answer: 'M',
        number: 62,
        clues: ['60A', '62D'],
      },
      {
        guess: '',
        answer: 'E',
        number: 63,
        clues: ['60A', '63D'],
      },
    ],
    [
      {
        guess: '',
        answer: 'A',
        number: 64,
        clues: ['64A', '56D'],
      },
      {
        guess: '',
        answer: 'F',
        number: null,
        clues: ['64A', '57D'],
      },
      {
        guess: '',
        answer: 'I',
        number: null,
        clues: ['64A', '58D'],
      },
      {
        guess: '',
        answer: 'N',
        number: null,
        clues: ['64A', '35D'],
      },
      {
        guess: '',
        answer: 'E',
        number: null,
        clues: ['64A', '53D'],
      },
      {
        answer: '#BlackSquare#',
      },
      {
        guess: '',
        answer: 'A',
        number: 65,
        clues: ['65A', '59D'],
      },
      {
        guess: '',
        answer: 'L',
        number: null,
        clues: ['65A', '45D'],
      },
      {
        guess: '',
        answer: 'L',
        number: null,
        clues: ['65A', '49D'],
      },
      {
        guess: '',
        answer: 'I',
        number: null,
        clues: ['65A', '50D'],
      },
      {
        guess: '',
        answer: 'G',
        number: 66,
        clues: ['65A', '66D'],
      },
      {
        guess: '',
        answer: 'A',
        number: null,
        clues: ['65A', '55D'],
      },
      {
        guess: '',
        answer: 'T',
        number: null,
        clues: ['65A', '61D'],
      },
      {
        guess: '',
        answer: 'O',
        number: null,
        clues: ['65A', '62D'],
      },
      {
        guess: '',
        answer: 'R',
        number: null,
        clues: ['65A', '63D'],
      },
    ],
    [
      {
        guess: '',
        answer: 'L',
        number: 67,
        clues: ['67A', '56D'],
      },
      {
        guess: '',
        answer: 'A',
        number: null,
        clues: ['67A', '57D'],
      },
      {
        guess: '',
        answer: 'K',
        number: null,
        clues: ['67A', '58D'],
      },
      {
        guess: '',
        answer: 'E',
        number: null,
        clues: ['67A', '35D'],
      },
      {
        guess: '',
        answer: 'R',
        number: null,
        clues: ['67A', '53D'],
      },
      {
        answer: '#BlackSquare#',
      },
      {
        guess: '',
        answer: 'D',
        number: 68,
        clues: ['68A', '59D'],
      },
      {
        guess: '',
        answer: 'E',
        number: null,
        clues: ['68A', '45D'],
      },
      {
        guess: '',
        answer: 'L',
        number: null,
        clues: ['68A', '49D'],
      },
      {
        guess: '',
        answer: 'T',
        number: null,
        clues: ['68A', '50D'],
      },
      {
        guess: '',
        answer: 'A',
        number: null,
        clues: ['68A', '66D'],
      },
      {
        guess: '',
        answer: 'W',
        number: null,
        clues: ['68A', '55D'],
      },
      {
        guess: '',
        answer: 'I',
        number: null,
        clues: ['68A', '61D'],
      },
      {
        guess: '',
        answer: 'N',
        number: null,
        clues: ['68A', '62D'],
      },
      {
        guess: '',
        answer: 'G',
        number: null,
        clues: ['68A', '63D'],
      },
    ],
    [
      {
        guess: '',
        answer: 'T',
        number: 69,
        clues: ['69A', '56D'],
      },
      {
        guess: '',
        answer: 'R',
        number: null,
        clues: ['69A', '57D'],
      },
      {
        guess: '',
        answer: 'E',
        number: null,
        clues: ['69A', '58D'],
      },
      {
        guess: '',
        answer: 'Y',
        number: null,
        clues: ['69A', '35D'],
      },
      {
        guess: '',
        answer: 'S',
        number: null,
        clues: ['69A', '53D'],
      },
      {
        answer: '#BlackSquare#',
      },
      {
        guess: '',
        answer: 'A',
        number: 70,
        clues: ['70A', '59D'],
      },
      {
        guess: '',
        answer: 'S',
        number: null,
        clues: ['70A', '45D'],
      },
      {
        guess: '',
        answer: 'S',
        number: null,
        clues: ['70A', '49D'],
      },
      {
        guess: '',
        answer: 'E',
        number: null,
        clues: ['70A', '50D'],
      },
      {
        guess: '',
        answer: 'T',
        number: null,
        clues: ['70A', '66D'],
      },
      {
        answer: '#BlackSquare#',
      },
      {
        guess: '',
        answer: 'S',
        number: 71,
        clues: ['71A', '61D'],
      },
      {
        guess: '',
        answer: 'O',
        number: null,
        clues: ['71A', '62D'],
      },
      {
        guess: '',
        answer: 'O',
        number: null,
        clues: ['71A', '63D'],
      },
    ],
  ],
  clues: {
    '1A': {
      answer: 'MIA',
      clue: '"___ Carlotta," T. A. Daly poem',
      position: '1A',
      __typename: 'Clue',
      cells: [[0, 0], [0, 1], [0, 2]],
    },
    '4A': {
      answer: 'CANES',
      clue: 'Works with rattan',
      position: '4A',
      __typename: 'Clue',
      cells: [[0, 4], [0, 5], [0, 6], [0, 7], [0, 8]],
    },
    '9A': {
      answer: 'SPOOL',
      clue: 'Line winder',
      position: '9A',
      __typename: 'Clue',
      cells: [[0, 10], [0, 11], [0, 12], [0, 13], [0, 14]],
    },
    '14A': {
      answer: 'INVARIANT',
      clue: 'Constant',
      position: '14A',
      __typename: 'Clue',
      cells: [
        [1, 0],
        [1, 1],
        [1, 2],
        [1, 3],
        [1, 4],
        [1, 5],
        [1, 6],
        [1, 7],
        [1, 8],
      ],
    },
    '16A': {
      answer: 'CATTY',
      clue: 'Spiteful',
      position: '16A',
      __typename: 'Clue',
      cells: [[1, 10], [1, 11], [1, 12], [1, 13], [1, 14]],
    },
    '17A': {
      answer: 'CROCODILE',
      clue: '"___ Dundee," 1986 movie',
      position: '17A',
      __typename: 'Clue',
      cells: [
        [2, 0],
        [2, 1],
        [2, 2],
        [2, 3],
        [2, 4],
        [2, 5],
        [2, 6],
        [2, 7],
        [2, 8],
      ],
    },
    '18A': {
      answer: 'AURIC',
      clue: 'Like many rings or watches',
      position: '18A',
      __typename: 'Clue',
      cells: [[2, 10], [2, 11], [2, 12], [2, 13], [2, 14]],
    },
    '19A': {
      answer: 'KENT',
      clue: 'Reeve role',
      position: '19A',
      __typename: 'Clue',
      cells: [[3, 0], [3, 1], [3, 2], [3, 3]],
    },
    '20A': {
      answer: 'ELIWALLACH',
      clue: 'Actor in 56 Across',
      position: '20A',
      __typename: 'Clue',
      cells: [
        [3, 5],
        [3, 6],
        [3, 7],
        [3, 8],
        [3, 9],
        [3, 10],
        [3, 11],
        [3, 12],
        [3, 13],
        [3, 14],
      ],
    },
    '22A': {
      answer: 'SIDES',
      clue: "A cube's sextet",
      position: '22A',
      __typename: 'Clue',
      cells: [[4, 3], [4, 4], [4, 5], [4, 6], [4, 7]],
    },
    '24A': {
      answer: 'BAH',
      clue: "Curmudgeon's cry",
      position: '24A',
      __typename: 'Clue',
      cells: [[4, 9], [4, 10], [4, 11]],
    },
    '25A': {
      answer: 'CAL',
      clue: 'Golfer Peete',
      position: '25A',
      __typename: 'Clue',
      cells: [[5, 0], [5, 1], [5, 2]],
    },
    '28A': {
      answer: 'BERTHA',
      clue: "Woman's wide, lacy collar",
      position: '28A',
      __typename: 'Clue',
      cells: [[5, 4], [5, 5], [5, 6], [5, 7], [5, 8], [5, 9]],
    },
    '30A': {
      answer: 'OPAL',
      clue: 'Gift for some Scorpios',
      position: '30A',
      __typename: 'Clue',
      cells: [[5, 11], [5, 12], [5, 13], [5, 14]],
    },
    '34A': {
      answer: 'AMOLE',
      clue: 'Soap plant',
      position: '34A',
      __typename: 'Clue',
      cells: [[6, 0], [6, 1], [6, 2], [6, 3], [6, 4]],
    },
    '36A': {
      answer: 'SOT',
      clue: 'Boozer',
      position: '36A',
      __typename: 'Clue',
      cells: [[6, 7], [6, 8], [6, 9]],
    },
    '37A': {
      answer: 'GALA',
      clue: 'Wingding',
      position: '37A',
      __typename: 'Clue',
      cells: [[6, 11], [6, 12], [6, 13], [6, 14]],
    },
    '38A': {
      answer: 'REBOXED',
      clue: 'Put in a new carton',
      position: '38A',
      __typename: 'Clue',
      cells: [[7, 0], [7, 1], [7, 2], [7, 3], [7, 4], [7, 5], [7, 6]],
    },
    '41A': {
      answer: 'BELATED',
      clue: 'Tardy',
      position: '41A',
      __typename: 'Clue',
      cells: [[7, 8], [7, 9], [7, 10], [7, 11], [7, 12], [7, 13], [7, 14]],
    },
    '43A': {
      answer: 'OBAN',
      clue: 'City in Scotland',
      position: '43A',
      __typename: 'Clue',
      cells: [[8, 0], [8, 1], [8, 2], [8, 3]],
    },
    '44A': {
      answer: 'NUB',
      clue: 'The real issue',
      position: '44A',
      __typename: 'Clue',
      cells: [[8, 5], [8, 6], [8, 7]],
    },
    '46A': {
      answer: 'ENTRY',
      clue: 'What some burglars gain',
      position: '46A',
      __typename: 'Clue',
      cells: [[8, 10], [8, 11], [8, 12], [8, 13], [8, 14]],
    },
    '47A': {
      answer: 'MARC',
      clue: 'Playwright Connelly',
      position: '47A',
      __typename: 'Clue',
      cells: [[9, 0], [9, 1], [9, 2], [9, 3]],
    },
    '48A': {
      answer: 'ODESSA',
      clue: 'Port on the Black Sea',
      position: '48A',
      __typename: 'Clue',
      cells: [[9, 5], [9, 6], [9, 7], [9, 8], [9, 9], [9, 10]],
    },
    '51A': {
      answer: 'ITS',
      clue: '"___ Magic," Doris Day hit',
      position: '51A',
      __typename: 'Clue',
      cells: [[9, 12], [9, 13], [9, 14]],
    },
    '52A': {
      answer: 'HAL',
      clue: 'Actor Linden',
      position: '52A',
      __typename: 'Clue',
      cells: [[10, 3], [10, 4], [10, 5]],
    },
    '54A': {
      answer: 'AMPHI',
      clue: 'Of both kinds: Comb. form',
      position: '54A',
      __typename: 'Clue',
      cells: [[10, 7], [10, 8], [10, 9], [10, 10], [10, 11]],
    },
    '56A': {
      answer: 'SALAMANDER',
      clue: '"The ___," 1981 movie',
      position: '56A',
      __typename: 'Clue',
      cells: [
        [11, 0],
        [11, 1],
        [11, 2],
        [11, 3],
        [11, 4],
        [11, 5],
        [11, 6],
        [11, 7],
        [11, 8],
        [11, 9],
      ],
    },
    '60A': {
      answer: 'SOME',
      clue: '"___ Enchanted Evening"',
      position: '60A',
      __typename: 'Clue',
      cells: [[11, 11], [11, 12], [11, 13], [11, 14]],
    },
    '64A': {
      answer: 'AFINE',
      clue: '"___ Romance"',
      position: '64A',
      __typename: 'Clue',
      cells: [[12, 0], [12, 1], [12, 2], [12, 3], [12, 4]],
    },
    '65A': {
      answer: 'ALLIGATOR',
      clue: '"The ___ People," 1959 movie',
      position: '65A',
      __typename: 'Clue',
      cells: [
        [12, 6],
        [12, 7],
        [12, 8],
        [12, 9],
        [12, 10],
        [12, 11],
        [12, 12],
        [12, 13],
        [12, 14],
      ],
    },
    '67A': {
      answer: 'LAKER',
      clue: 'Abdul-Jabbar was one',
      position: '67A',
      __typename: 'Clue',
      cells: [[13, 0], [13, 1], [13, 2], [13, 3], [13, 4]],
    },
    '68A': {
      answer: 'DELTAWING',
      clue: 'Jet design',
      position: '68A',
      __typename: 'Clue',
      cells: [
        [13, 6],
        [13, 7],
        [13, 8],
        [13, 9],
        [13, 10],
        [13, 11],
        [13, 12],
        [13, 13],
        [13, 14],
      ],
    },
    '69A': {
      answer: 'TREYS',
      clue: 'Dice throws',
      position: '69A',
      __typename: 'Clue',
      cells: [[14, 0], [14, 1], [14, 2], [14, 3], [14, 4]],
    },
    '70A': {
      answer: 'ASSET',
      clue: 'A strong point',
      position: '70A',
      __typename: 'Clue',
      cells: [[14, 6], [14, 7], [14, 8], [14, 9], [14, 10]],
    },
    '71A': {
      answer: 'SOO',
      clue: 'Mich. locks, for short',
      position: '71A',
      __typename: 'Clue',
      cells: [[14, 12], [14, 13], [14, 14]],
    },
    '1D': {
      answer: 'MICK',
      clue: 'Rocker Jagger',
      position: '1D',
      __typename: 'Clue',
      cells: [[0, 0], [1, 0], [2, 0], [3, 0]],
    },
    '2D': {
      answer: 'INRE',
      clue: 'Concerning',
      position: '2D',
      __typename: 'Clue',
      cells: [[0, 1], [1, 1], [2, 1], [3, 1]],
    },
    '3D': {
      answer: 'AVON',
      clue: "Bath's county",
      position: '3D',
      __typename: 'Clue',
      cells: [[0, 2], [1, 2], [2, 2], [3, 2]],
    },
    '4D': {
      answer: 'CRO',
      clue: '___-Magnon',
      position: '4D',
      __typename: 'Clue',
      cells: [[0, 4], [1, 4], [2, 4]],
    },
    '5D': {
      answer: 'AIDEDE',
      clue: '___-camp',
      position: '5D',
      __typename: 'Clue',
      cells: [[0, 5], [1, 5], [2, 5], [3, 5], [4, 5], [5, 5]],
    },
    '6D': {
      answer: 'NAILER',
      clue: 'Carpenter, often',
      position: '6D',
      __typename: 'Clue',
      cells: [[0, 6], [1, 6], [2, 6], [3, 6], [4, 6], [5, 6]],
    },
    '7D': {
      answer: 'ENLISTS',
      clue: "Gets one's help",
      position: '7D',
      __typename: 'Clue',
      cells: [[0, 7], [1, 7], [2, 7], [3, 7], [4, 7], [5, 7], [6, 7]],
    },
    '8D': {
      answer: 'STEW',
      clue: 'Jugged hare, e.g.',
      position: '8D',
      __typename: 'Clue',
      cells: [[0, 8], [1, 8], [2, 8], [3, 8]],
    },
    '9D': {
      answer: 'SCALA',
      clue: "Milan's La ___ Opera House",
      position: '9D',
      __typename: 'Clue',
      cells: [[0, 10], [1, 10], [2, 10], [3, 10], [4, 10]],
    },
    '10D': {
      answer: 'PAULHOGAN',
      clue: 'Star of 17 Across',
      position: '10D',
      __typename: 'Clue',
      cells: [
        [0, 11],
        [1, 11],
        [2, 11],
        [3, 11],
        [4, 11],
        [5, 11],
        [6, 11],
        [7, 11],
        [8, 11],
      ],
    },
    '11D': {
      answer: 'OTRA',
      clue: 'Norwegian river',
      position: '11D',
      __typename: 'Clue',
      cells: [[0, 12], [1, 12], [2, 12], [3, 12]],
    },
    '12D': {
      answer: 'OTIC',
      clue: 'Of hearing',
      position: '12D',
      __typename: 'Clue',
      cells: [[0, 13], [1, 13], [2, 13], [3, 13]],
    },
    '13D': {
      answer: 'LYCH',
      clue: "Churchyard's ___ gate",
      position: '13D',
      __typename: 'Clue',
      cells: [[0, 14], [1, 14], [2, 14], [3, 14]],
    },
    '15D': {
      answer: 'ACTS',
      clue: 'Biblical book',
      position: '15D',
      __typename: 'Clue',
      cells: [[1, 3], [2, 3], [3, 3], [4, 3]],
    },
    '21D': {
      answer: 'ABATE',
      clue: 'Simmer down',
      position: '21D',
      __typename: 'Clue',
      cells: [[3, 9], [4, 9], [5, 9], [6, 9], [7, 9]],
    },
    '23D': {
      answer: 'IBEX',
      clue: 'Wild goat',
      position: '23D',
      __typename: 'Clue',
      cells: [[4, 4], [5, 4], [6, 4], [7, 4]],
    },
    '25D': {
      answer: 'CAROM',
      clue: 'Billiard shot',
      position: '25D',
      __typename: 'Clue',
      cells: [[5, 0], [6, 0], [7, 0], [8, 0], [9, 0]],
    },
    '26D': {
      answer: 'AMEBA',
      clue: 'Very simple animal',
      position: '26D',
      __typename: 'Clue',
      cells: [[5, 1], [6, 1], [7, 1], [8, 1], [9, 1]],
    },
    '27D': {
      answer: 'LOBAR',
      clue: 'Of a part of the lungs',
      position: '27D',
      __typename: 'Clue',
      cells: [[5, 2], [6, 2], [7, 2], [8, 2], [9, 2]],
    },
    '29D': {
      answer: 'HOB',
      clue: 'Raise ___ (behave destructively)',
      position: '29D',
      __typename: 'Clue',
      cells: [[5, 8], [6, 8], [7, 8]],
    },
    '31D': {
      answer: 'PATTI',
      clue: 'Page or LuPone',
      position: '31D',
      __typename: 'Clue',
      cells: [[5, 12], [6, 12], [7, 12], [8, 12], [9, 12]],
    },
    '32D': {
      answer: 'ALERT',
      clue: 'Argus-eyed',
      position: '32D',
      __typename: 'Clue',
      cells: [[5, 13], [6, 13], [7, 13], [8, 13], [9, 13]],
    },
    '33D': {
      answer: 'LADYS',
      clue: '___-slipper (orchid)',
      position: '33D',
      __typename: 'Clue',
      cells: [[5, 14], [6, 14], [7, 14], [8, 14], [9, 14]],
    },
    '35D': {
      answer: 'LONCHANEY',
      clue: 'Actor in 65 Across',
      position: '35D',
      __typename: 'Clue',
      cells: [
        [6, 3],
        [7, 3],
        [8, 3],
        [9, 3],
        [10, 3],
        [11, 3],
        [12, 3],
        [13, 3],
        [14, 3],
      ],
    },
    '39D': {
      answer: 'ENOLA',
      clue: '___ Gay, W.W. II bomber',
      position: '39D',
      __typename: 'Clue',
      cells: [[7, 5], [8, 5], [9, 5], [10, 5], [11, 5]],
    },
    '40D': {
      answer: 'DUD',
      clue: 'Clinker',
      position: '40D',
      __typename: 'Clue',
      cells: [[7, 6], [8, 6], [9, 6]],
    },
    '42D': {
      answer: 'LEAH',
      clue: 'A wife of Jacob',
      position: '42D',
      __typename: 'Clue',
      cells: [[7, 10], [8, 10], [9, 10], [10, 10]],
    },
    '45D': {
      answer: 'BEADLES',
      clue: 'Parish officers',
      position: '45D',
      __typename: 'Clue',
      cells: [[8, 7], [9, 7], [10, 7], [11, 7], [12, 7], [13, 7], [14, 7]],
    },
    '49D': {
      answer: 'SMELLS',
      clue: 'Whiffs',
      position: '49D',
      __typename: 'Clue',
      cells: [[9, 8], [10, 8], [11, 8], [12, 8], [13, 8], [14, 8]],
    },
    '50D': {
      answer: 'SPRITE',
      clue: 'Tinker Bell, e.g.',
      position: '50D',
      __typename: 'Clue',
      cells: [[9, 9], [10, 9], [11, 9], [12, 9], [13, 9], [14, 9]],
    },
    '53D': {
      answer: 'AMERS',
      clue: 'Natives of the U.S.A.',
      position: '53D',
      __typename: 'Clue',
      cells: [[10, 4], [11, 4], [12, 4], [13, 4], [14, 4]],
    },
    '55D': {
      answer: 'ISAW',
      clue: '"Was it a cat ___?"',
      position: '55D',
      __typename: 'Clue',
      cells: [[10, 11], [11, 11], [12, 11], [13, 11]],
    },
    '56D': {
      answer: 'SALT',
      clue: 'Shaker contents',
      position: '56D',
      __typename: 'Clue',
      cells: [[11, 0], [12, 0], [13, 0], [14, 0]],
    },
    '57D': {
      answer: 'AFAR',
      clue: 'Almost out of sight',
      position: '57D',
      __typename: 'Clue',
      cells: [[11, 1], [12, 1], [13, 1], [14, 1]],
    },
    '58D': {
      answer: 'LIKE',
      clue: 'Much the same as',
      position: '58D',
      __typename: 'Clue',
      cells: [[11, 2], [12, 2], [13, 2], [14, 2]],
    },
    '59D': {
      answer: 'NADA',
      clue: "It's nothing to Juan",
      position: '59D',
      __typename: 'Clue',
      cells: [[11, 6], [12, 6], [13, 6], [14, 6]],
    },
    '61D': {
      answer: 'OTIS',
      clue: 'Name in lifts',
      position: '61D',
      __typename: 'Clue',
      cells: [[11, 12], [12, 12], [13, 12], [14, 12]],
    },
    '62D': {
      answer: 'MONO',
      clue: 'Kind of rail',
      position: '62D',
      __typename: 'Clue',
      cells: [[11, 13], [12, 13], [13, 13], [14, 13]],
    },
    '63D': {
      answer: 'ERGO',
      clue: 'Therefore',
      position: '63D',
      __typename: 'Clue',
      cells: [[11, 14], [12, 14], [13, 14], [14, 14]],
    },
    '66D': {
      answer: 'GAT',
      clue: "Thug's heater",
      position: '66D',
      __typename: 'Clue',
      cells: [[12, 10], [13, 10], [14, 10]],
    },
  },
};
