export default {
  _id: '5c579a79d406c202c41d847e',
  board: [
    [
      'M',
      'I',
      'A',
      '#BlackSquare#',
      'C',
      'A',
      'N',
      'E',
      'S',
      '#BlackSquare#',
      'S',
      'P',
      'O',
      'O',
      'L',
    ],
    [
      'I',
      'N',
      'V',
      'A',
      'R',
      'I',
      'A',
      'N',
      'T',
      '#BlackSquare#',
      'C',
      'A',
      'T',
      'T',
      'Y',
    ],
    [
      'C',
      'R',
      'O',
      'C',
      'O',
      'D',
      'I',
      'L',
      'E',
      '#BlackSquare#',
      'A',
      'U',
      'R',
      'I',
      'C',
    ],
    [
      'K',
      'E',
      'N',
      'T',
      '#BlackSquare#',
      'E',
      'L',
      'I',
      'W',
      'A',
      'L',
      'L',
      'A',
      'C',
      'H',
    ],
    [
      '#BlackSquare#',
      '#BlackSquare#',
      '#BlackSquare#',
      'S',
      'I',
      'D',
      'E',
      'S',
      '#BlackSquare#',
      'B',
      'A',
      'H',
      '#BlackSquare#',
      '#BlackSquare#',
      '#BlackSquare#',
    ],
    [
      'C',
      'A',
      'L',
      '#BlackSquare#',
      'B',
      'E',
      'R',
      'T',
      'H',
      'A',
      '#BlackSquare#',
      'O',
      'P',
      'A',
      'L',
    ],
    [
      'A',
      'M',
      'O',
      'L',
      'E',
      '#BlackSquare#',
      '#BlackSquare#',
      'S',
      'O',
      'T',
      '#BlackSquare#',
      'G',
      'A',
      'L',
      'A',
    ],
    [
      'R',
      'E',
      'B',
      'O',
      'X',
      'E',
      'D',
      '#BlackSquare#',
      'B',
      'E',
      'L',
      'A',
      'T',
      'E',
      'D',
    ],
    [
      'O',
      'B',
      'A',
      'N',
      '#BlackSquare#',
      'N',
      'U',
      'B',
      '#BlackSquare#',
      '#BlackSquare#',
      'E',
      'N',
      'T',
      'R',
      'Y',
    ],
    [
      'M',
      'A',
      'R',
      'C',
      '#BlackSquare#',
      'O',
      'D',
      'E',
      'S',
      'S',
      'A',
      '#BlackSquare#',
      'I',
      'T',
      'S',
    ],
    [
      '#BlackSquare#',
      '#BlackSquare#',
      '#BlackSquare#',
      'H',
      'A',
      'L',
      '#BlackSquare#',
      'A',
      'M',
      'P',
      'H',
      'I',
      '#BlackSquare#',
      '#BlackSquare#',
      '#BlackSquare#',
    ],
    [
      'S',
      'A',
      'L',
      'A',
      'M',
      'A',
      'N',
      'D',
      'E',
      'R',
      '#BlackSquare#',
      'S',
      'O',
      'M',
      'E',
    ],
    [
      'A',
      'F',
      'I',
      'N',
      'E',
      '#BlackSquare#',
      'A',
      'L',
      'L',
      'I',
      'G',
      'A',
      'T',
      'O',
      'R',
    ],
    [
      'L',
      'A',
      'K',
      'E',
      'R',
      '#BlackSquare#',
      'D',
      'E',
      'L',
      'T',
      'A',
      'W',
      'I',
      'N',
      'G',
    ],
    [
      'T',
      'R',
      'E',
      'Y',
      'S',
      '#BlackSquare#',
      'A',
      'S',
      'S',
      'E',
      'T',
      '#BlackSquare#',
      'S',
      'O',
      'O',
    ],
  ],
  title: 'New York Times, Thursday, September 6, 1990',
  date: '9/6/1990',
  publisher: 'New York Times',
  editor: 'Eugene T. Maleska',
  author: 'Nancy W. Atkinson',
  dimensions: {
    rows: 15,
    columns: 15,
  },
  clues: [
    {
      answer: 'MIA',
      clue: '"___ Carlotta," T. A. Daly poem',
      position: '1A',
      __typename: 'Clue',
    },
    {
      answer: 'CANES',
      clue: 'Works with rattan',
      position: '4A',
      __typename: 'Clue',
    },
    {
      answer: 'SPOOL',
      clue: 'Line winder',
      position: '9A',
      __typename: 'Clue',
    },
    {
      answer: 'INVARIANT',
      clue: 'Constant',
      position: '14A',
      __typename: 'Clue',
    },
    { answer: 'CATTY', clue: 'Spiteful', position: '16A', __typename: 'Clue' },
    {
      answer: 'CROCODILE',
      clue: '"___ Dundee," 1986 movie',
      position: '17A',
      __typename: 'Clue',
    },
    {
      answer: 'AURIC',
      clue: 'Like many rings or watches',
      position: '18A',
      __typename: 'Clue',
    },
    { answer: 'KENT', clue: 'Reeve role', position: '19A', __typename: 'Clue' },
    {
      answer: 'ELIWALLACH',
      clue: 'Actor in 56 Across',
      position: '20A',
      __typename: 'Clue',
    },
    {
      answer: 'SIDES',
      clue: "A cube's sextet",
      position: '22A',
      __typename: 'Clue',
    },
    {
      answer: 'BAH',
      clue: "Curmudgeon's cry",
      position: '24A',
      __typename: 'Clue',
    },
    {
      answer: 'CAL',
      clue: 'Golfer Peete',
      position: '25A',
      __typename: 'Clue',
    },
    {
      answer: 'BERTHA',
      clue: "Woman's wide, lacy collar",
      position: '28A',
      __typename: 'Clue',
    },
    {
      answer: 'OPAL',
      clue: 'Gift for some Scorpios',
      position: '30A',
      __typename: 'Clue',
    },
    {
      answer: 'AMOLE',
      clue: 'Soap plant',
      position: '34A',
      __typename: 'Clue',
    },
    { answer: 'SOT', clue: 'Boozer', position: '36A', __typename: 'Clue' },
    { answer: 'GALA', clue: 'Wingding', position: '37A', __typename: 'Clue' },
    {
      answer: 'REBOXED',
      clue: 'Put in a new carton',
      position: '38A',
      __typename: 'Clue',
    },
    { answer: 'BELATED', clue: 'Tardy', position: '41A', __typename: 'Clue' },
    {
      answer: 'OBAN',
      clue: 'City in Scotland',
      position: '43A',
      __typename: 'Clue',
    },
    {
      answer: 'NUB',
      clue: 'The real issue',
      position: '44A',
      __typename: 'Clue',
    },
    {
      answer: 'ENTRY',
      clue: 'What some burglars gain',
      position: '46A',
      __typename: 'Clue',
    },
    {
      answer: 'MARC',
      clue: 'Playwright Connelly',
      position: '47A',
      __typename: 'Clue',
    },
    {
      answer: 'ODESSA',
      clue: 'Port on the Black Sea',
      position: '48A',
      __typename: 'Clue',
    },
    {
      answer: 'ITS',
      clue: '"___ Magic," Doris Day hit',
      position: '51A',
      __typename: 'Clue',
    },
    {
      answer: 'HAL',
      clue: 'Actor Linden',
      position: '52A',
      __typename: 'Clue',
    },
    {
      answer: 'AMPHI',
      clue: 'Of both kinds: Comb. form',
      position: '54A',
      __typename: 'Clue',
    },
    {
      answer: 'SALAMANDER',
      clue: '"The ___," 1981 movie',
      position: '56A',
      __typename: 'Clue',
    },
    {
      answer: 'SOME',
      clue: '"___ Enchanted Evening"',
      position: '60A',
      __typename: 'Clue',
    },
    {
      answer: 'AFINE',
      clue: '"___ Romance"',
      position: '64A',
      __typename: 'Clue',
    },
    {
      answer: 'ALLIGATOR',
      clue: '"The ___ People," 1959 movie',
      position: '65A',
      __typename: 'Clue',
    },
    {
      answer: 'LAKER',
      clue: 'Abdul-Jabbar was one',
      position: '67A',
      __typename: 'Clue',
    },
    {
      answer: 'DELTAWING',
      clue: 'Jet design',
      position: '68A',
      __typename: 'Clue',
    },
    {
      answer: 'TREYS',
      clue: 'Dice throws',
      position: '69A',
      __typename: 'Clue',
    },
    {
      answer: 'ASSET',
      clue: 'A strong point',
      position: '70A',
      __typename: 'Clue',
    },
    {
      answer: 'SOO',
      clue: 'Mich. locks, for short',
      position: '71A',
      __typename: 'Clue',
    },
    {
      answer: 'MICK',
      clue: 'Rocker Jagger',
      position: '1D',
      __typename: 'Clue',
    },
    { answer: 'INRE', clue: 'Concerning', position: '2D', __typename: 'Clue' },
    {
      answer: 'AVON',
      clue: "Bath's county",
      position: '3D',
      __typename: 'Clue',
    },
    { answer: 'CRO', clue: '___-Magnon', position: '4D', __typename: 'Clue' },
    { answer: 'AIDEDE', clue: '___-camp', position: '5D', __typename: 'Clue' },
    {
      answer: 'NAILER',
      clue: 'Carpenter, often',
      position: '6D',
      __typename: 'Clue',
    },
    {
      answer: 'ENLISTS',
      clue: "Gets one's help",
      position: '7D',
      __typename: 'Clue',
    },
    {
      answer: 'STEW',
      clue: 'Jugged hare, e.g.',
      position: '8D',
      __typename: 'Clue',
    },
    {
      answer: 'SCALA',
      clue: "Milan's La ___ Opera House",
      position: '9D',
      __typename: 'Clue',
    },
    {
      answer: 'PAULHOGAN',
      clue: 'Star of 17 Across',
      position: '10D',
      __typename: 'Clue',
    },
    {
      answer: 'OTRA',
      clue: 'Norwegian river',
      position: '11D',
      __typename: 'Clue',
    },
    { answer: 'OTIC', clue: 'Of hearing', position: '12D', __typename: 'Clue' },
    {
      answer: 'LYCH',
      clue: "Churchyard's ___ gate",
      position: '13D',
      __typename: 'Clue',
    },
    {
      answer: 'ACTS',
      clue: 'Biblical book',
      position: '15D',
      __typename: 'Clue',
    },
    {
      answer: 'ABATE',
      clue: 'Simmer down',
      position: '21D',
      __typename: 'Clue',
    },
    { answer: 'IBEX', clue: 'Wild goat', position: '23D', __typename: 'Clue' },
    {
      answer: 'CAROM',
      clue: 'Billiard shot',
      position: '25D',
      __typename: 'Clue',
    },
    {
      answer: 'AMEBA',
      clue: 'Very simple animal',
      position: '26D',
      __typename: 'Clue',
    },
    {
      answer: 'LOBAR',
      clue: 'Of a part of the lungs',
      position: '27D',
      __typename: 'Clue',
    },
    {
      answer: 'HOB',
      clue: 'Raise ___ (behave destructively)',
      position: '29D',
      __typename: 'Clue',
    },
    {
      answer: 'PATTI',
      clue: 'Page or LuPone',
      position: '31D',
      __typename: 'Clue',
    },
    {
      answer: 'ALERT',
      clue: 'Argus-eyed',
      position: '32D',
      __typename: 'Clue',
    },
    {
      answer: 'LADYS',
      clue: '___-slipper (orchid)',
      position: '33D',
      __typename: 'Clue',
    },
    {
      answer: 'LONCHANEY',
      clue: 'Actor in 65 Across',
      position: '35D',
      __typename: 'Clue',
    },
    {
      answer: 'ENOLA',
      clue: '___ Gay, W.W. II bomber',
      position: '39D',
      __typename: 'Clue',
    },
    { answer: 'DUD', clue: 'Clinker', position: '40D', __typename: 'Clue' },
    {
      answer: 'LEAH',
      clue: 'A wife of Jacob',
      position: '42D',
      __typename: 'Clue',
    },
    {
      answer: 'BEADLES',
      clue: 'Parish officers',
      position: '45D',
      __typename: 'Clue',
    },
    { answer: 'SMELLS', clue: 'Whiffs', position: '49D', __typename: 'Clue' },
    {
      answer: 'SPRITE',
      clue: 'Tinker Bell, e.g.',
      position: '50D',
      __typename: 'Clue',
    },
    {
      answer: 'AMERS',
      clue: 'Natives of the U.S.A.',
      position: '53D',
      __typename: 'Clue',
    },
    {
      answer: 'ISAW',
      clue: '"Was it a cat ___?"',
      position: '55D',
      __typename: 'Clue',
    },
    {
      answer: 'SALT',
      clue: 'Shaker contents',
      position: '56D',
      __typename: 'Clue',
    },
    {
      answer: 'AFAR',
      clue: 'Almost out of sight',
      position: '57D',
      __typename: 'Clue',
    },
    {
      answer: 'LIKE',
      clue: 'Much the same as',
      position: '58D',
      __typename: 'Clue',
    },
    {
      answer: 'NADA',
      clue: "It's nothing to Juan",
      position: '59D',
      __typename: 'Clue',
    },
    {
      answer: 'OTIS',
      clue: 'Name in lifts',
      position: '61D',
      __typename: 'Clue',
    },
    {
      answer: 'MONO',
      clue: 'Kind of rail',
      position: '62D',
      __typename: 'Clue',
    },
    { answer: 'ERGO', clue: 'Therefore', position: '63D', __typename: 'Clue' },
    {
      answer: 'GAT',
      clue: "Thug's heater",
      position: '66D',
      __typename: 'Clue',
    },
  ],
};
